[config]

[templates.niri]
input_path = '~/.config/matugen/templates/niri.kdl'
output_path = '~/.config/niri/matugen.kdl'
post_hook = 'niri msg action load-config-file'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update &'

[templates.fcitx5]
input_path = '~/.config/matugen/templates/fcitx5/fcitx5-theme.conf'
output_path = '~/.local/share/fcitx5/themes/Matugen/theme.conf'
post_hook = '~/.config/matugen/templates/fcitx5/fcitx5.sh; fcitx5 -r & disown '

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.btop]
input_path = '~/.config/matugen/templates/btop/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'killall -SIGUSR1 btop 2>/dev/null || true; killall -SIGUSR2 btop 2>/dev/null || true'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

# [templates.cava]
# input_path = '~/.config/matugen/templates/cava-colors.ini'
# output_path = '~/.config/cava/themes/your-theme'
# post_hook = "pkill -USR1 cava"

# [templates.starship]
# input_path = '~/.config/matugen/templates/starship-colors.toml'
# output_path = '~/.config/starship.toml'

[templates.gtk-folder]
input_path = '~/.config/matugen/templates/gtk-folder/recolor.sh'
output_path = '~/.cache/matugen/recoloricons.sh'
post_hook = 'bash ~/.cache/matugen/recoloricons.sh &'

# [templates.fastfetch]
# input_path = '~/.config/matugen/templates/fastfetch-config.jsonc'
# output_path = '~/.config/fastfetch/config.jsonc'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.gtk3]
input_path = '~/.config/matugen/matugen-themes/templates/gtk3-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/matugen-themes/templates/gtk4-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = '~/.config/matugen/matugen-themes/post-hook-scripts/gtk-themes-reload.sh {{mode}}'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qt/qt5ct.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qt/qt6ct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'
