# --- Main Colors ---
background            #11140f
foreground            #e0e4da
cursor                #e0e4da
cursor_text_color     #11140f

selection_background  #3c4b38
selection_foreground  #d6e8ce

url_color             #a0cfd3

# --- ANSI Colors ---
color0                #11140f
color1                #ffb4ab
color2                #a0cfd3
color3                #baccb2
color4                #a3d398
color5                #a0cfd3
color6                #baccb2
color7                #e0e4da

color8                #42493f
color9                #93000a
color10               #1e4d51
color11               #3c4b38
color12               #265022
color13               #3c4b38
color14               #1e4d51
color15               #c2c8bc

# --- Starship Prompt Bubbles ---
color255              #265022
color254              #a3d398
color253              #3c4b38
color252              #baccb2
color251              #1e4d51
color250              #a0cfd3
color249              #93000a
color248              #ffb4ab

color232              #bef0b2
color233              #0e380d
color234              #d6e8ce
color235              #263422
color236              #bcebef
color237              #00363a
color238              #ffdad6
color239              #690005
color240              #bef0b2

# Matched with unthemed light/dark
color243              #a3d398
color244              #ffb4ab
color245              #42493f

# --- UI Elements ---
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   2.5 1.5
tab_bar_margin_color    #11140f

tab_bar_background              #11140f

active_tab_foreground           #0e380d
active_tab_background           #a3d398
active_tab_font_style           bold

inactive_tab_foreground         #bef0b2
inactive_tab_background         #265022
inactive_tab_font_style         normal

tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"

# --- Marks ---
mark1_foreground        #002202
mark1_background        #bef0b2
mark2_foreground        #111f0f
mark2_background        #d6e8ce
mark3_foreground        #002022
mark3_background        #bcebef
