window_padding_width 5
initial_window_width  70c
initial_window_height 20c
hide_window_decorations yes
background_opacity 0.85
font_family Maple Mono NL NF CN
font_size 13.5
remember_window_size no
confirm_os_window_close 0
shell zsh
allow_remote_control yes

cursor_trail 1
cursor_trail_decay 0.15 0.4
cursor_trail_start_threshold 1
cursor_shape block
shell_integration no-cursor

enabled_layouts splits
map ctrl+shift+backslash launch --location=vsplit
map ctrl+shift+enter launch --location=hsplit

# ===== Hints prefix: Ctrl+Shift+R =====
# Menu
map ctrl+shift+e kitten hints_menu.py

# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
