# --- Main Colors ---
background            #10140f
foreground            #e0e4db
cursor                #e0e4db
cursor_text_color     #10140f

selection_background  #3b4b39
selection_foreground  #d5e8cf

url_color             #a1ced5

# --- ANSI Colors ---
color0                #10140f
color1                #ffb4ab
color2                #a1ced5
color3                #b9ccb4
color4                #a0d49b
color5                #a1ced5
color6                #b9ccb4
color7                #e0e4db

color8                #424940
color9                #93000a
color10               #1f4d53
color11               #3b4b39
color12               #225025
color13               #3b4b39
color14               #1f4d53
color15               #c2c9bd

# --- Starship Prompt Bubbles ---
color255              #225025
color254              #a0d49b
color253              #3b4b39
color252              #b9ccb4
color251              #1f4d53
color250              #a1ced5
color249              #93000a
color248              #ffb4ab

color232              #bbf0b5
color233              #083910
color234              #d5e8cf
color235              #253423
color236              #bcebf1
color237              #00363b
color238              #ffdad6
color239              #690005
color240              #bbf0b5

# Matched with unthemed light/dark
color243              #a0d49b
color244              #ffb4ab
color245              #424940

# --- UI Elements ---
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   2.5 1.5
tab_bar_margin_color    #10140f

tab_bar_background              #10140f

active_tab_foreground           #083910
active_tab_background           #a0d49b
active_tab_font_style           bold

inactive_tab_foreground         #bbf0b5
inactive_tab_background         #225025
inactive_tab_font_style         normal

tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"

# --- Marks ---
mark1_foreground        #002105
mark1_background        #bbf0b5
mark2_foreground        #101f10
mark2_background        #d5e8cf
mark3_foreground        #001f23
mark3_background        #bcebf1
